/* Generated by automated build script */
#define SNAPSHOT
#define TEXTVER "Development snapshot 2015-11-09.a454399"
#define SSHVER "PuTTY-Snapshot-2015-11-09.a454399"
#define BINARY_VERSION 0,66,1002,0
